{
  # Keep imports static; feature defaults decide activation and dependencies.
  imports = [
    ./home-manager
    ./public-services
    ./code-server
    ./sunshine
    ./cloudflare-ddns
    ./cloudflare-public-cnames
    ./dns
    ./docker
    ./forgejo
    ./forgejo-actions-runner
    ./groupware
    ./immich
    ./incus
    ./jellyfin
    ./karakeep
    ./mailserver
    ./mineos
    ./ollama
    ./open-terminal
    ./opencloud
    ./openssh
    ./searxng
    ./swarm
    ./traefik
    ./vaultwarden
    ./wireguard-server
    ./ytdl-sub
    ./zed
    ./atcoder
    ./desktop-theme
    ./discord
    ./fcitx5
    ./floorp
    ./fonts
    ./foot
    ./greeter
    ./hyprland
    ./linux-wallpaperengine
    ./login-pin
    ./limine
    ./noctalia
    ./open-deck-desktop
    ./opencloud-client
    ./pandora-launcher
    ./paseo
    ./pcmanfm
    ./pi
    ./pipeasio
    ./pipewire
    ./solaar
    ./ssh
    ./steam
    ./thunderbird
    ./userDirs
    ./vscode
    ./wireguard-client
    ./zsh
  ];
}
