{
  # Keep imports static; feature defaults decide activation and dependencies.
  imports = [
    ./home-manager
    ./public-services
    ./cloudflare-ddns
    ./cloudflare-public-cnames
    ./dns
    ./docker
    ./openssh
    ./swarm
    ./traefik
    ./discord
    ./fcitx5
    ./floorp
    ./fonts
    ./foot
    ./greeter
    ./hyprland
    ./linux-wallpaperengine
    ./login-pin
    ./noctalia
    ./open-deck-desktop
    ./opencloud-client
    ./pandora-launcher
    ./paseo
    ./pcmanfm
    ./pi
    ./pipeasio
    ./pipewire
    ./solaar
    ./ssh
    ./thunderbird
    ./userDirs
    ./vscode
    ./zsh
  ];
}
