{ config, lib, ... }:
let
  ps = import ../public-services/lib.nix { inherit lib; };
  selected = ps.select config "sunshine";
in
{
  imports = [
    ./nixos.nix
    ../hyprland
    ../steam
  ];

  options.modules.public-services = ps.option "sunshine" (
    ps.common "Sunshine game streaming host"
    // {
      settings = lib.mkOption {
        type = lib.types.attrsOf (
          lib.types.oneOf [
            lib.types.str
            lib.types.bool
            lib.types.int
            lib.types.float
          ]
        );
        default = { };
        description = "Sunshine key/value settings, merged over the shared defaults; no secrets or pairing state.";
      };
      apps = lib.mkOption {
        default = null;
        description = "Replacement Sunshine application list; null retains Desktop and Steam Big Picture defaults. Commands are runtime strings, not shell wrappers generated by the module.";
        type = lib.types.nullOr (
          lib.types.listOf (
            lib.types.submodule {
              options = {
                name = lib.mkOption {
                  type = lib.types.nonEmptyStr;
                  description = "Application name shown to Moonlight clients.";
                };
                image-path = lib.mkOption {
                  type = lib.types.nullOr lib.types.nonEmptyStr;
                  default = null;
                  description = "Optional Sunshine application artwork path.";
                };
                cmd = lib.mkOption {
                  type = lib.types.nullOr lib.types.nonEmptyStr;
                  default = null;
                  description = "Optional foreground application command.";
                };
                detached = lib.mkOption {
                  type = lib.types.listOf lib.types.nonEmptyStr;
                  default = [ ];
                  description = "Detached application commands executed by Sunshine.";
                };
                prep-cmd = lib.mkOption {
                  default = [ ];
                  description = "Ordered preparation and cleanup command pairs.";
                  type = lib.types.listOf (
                    lib.types.submodule {
                      options = {
                        do = lib.mkOption {
                          type = lib.types.str;
                          default = "";
                          description = "Preparation command; empty means no preparation.";
                        };
                        undo = lib.mkOption {
                          type = lib.types.str;
                          default = "";
                          description = "Cleanup command; empty means no cleanup.";
                        };
                      };
                    }
                  );
                };
              };
            }
          )
        );
      };
      waitForHeadlessOutput = lib.mkEnableOption "waiting for the shared Hyprland headless output (requires hyprland.headless.enable on the owning OS)";
      backendUrl = lib.mkOption {
        type = lib.types.nullOr lib.types.nonEmptyStr;
        default = null;
        description = "Sunshine Web UI upstream reachable by the gateway; required when enabled. Streaming ports are configured separately by the consumer.";
      };
    }
  );

  config = lib.mkMerge [
    { assertions = selected.assertions; }
    (lib.mkIf selected.enabled {
      modules.hyprland.enable = true;
      modules.steam.enable = true;
    })
  ];
}
