# nix-instantiate --eval --strict tests/limine.nix \
#   --arg nixpkgs /path/to/nixpkgs --arg homeManager /path/to/home-manager
{
  nixpkgs,
  homeManager,
  system ? builtins.currentSystem,
}:
let
  t = import ./lib.nix { inherit nixpkgs homeManager system; };
  inherit (t) pkgs lib;

  base = t.cfgFor [ ];
  enabled = t.cfgFor [ { modules.limine.enable = true; } ];
  # A valid tiny image generated by Nix; evaluation never builds it or fetches a host logo.
  image = pkgs.writeText "splash.ppm" ''
    P3
    1 1
    255
    255 255 255
  '';
  themePackage = t.attopkgs.centered-plymouth-theme { inherit image; };
  disabledWithImage = t.cfgFor [ { modules.limine.splashImage = image; } ];
  custom = t.cfgFor [
    {
      modules.limine = {
        enable = true;
        splashImage = image;
      };
    }
  ];
  nativeThemePackage = pkgs.runCommand "native-plymouth-theme" { } "mkdir -p $out";
  customOverridden = t.cfgFor [
    {
      modules.limine = {
        enable = true;
        splashImage = image;
      };
      boot.plymouth = {
        theme = "native-theme";
        themePackages = [ nativeThemePackage ];
      };
    }
  ];
  overridden = t.cfgFor [
    {
      modules.limine = {
        enable = true;
        splashImage = image;
      };
    }
    {
      boot = {
        kernelPackages = pkgs.linuxPackages_latest;
        kernelParams = lib.mkForce [
          "debug"
          "loglevel=7"
        ];
        consoleLogLevel = 7;
        initrd.verbose = true;
        plymouth.enable = false;
        loader = {
          limine.maxGenerations = 3;
          efi.canTouchEfiVariables = false;
        };
      };
    }
  ];
  defaultParams = [
    "quiet"
    "udev.log_level=3"
    "rd.systemd.show_status=auto"
  ];
  unsafeParams = [
    "mitigations=off"
    "nowatchdog"
    "nmi_watchdog=0"
  ];
in
assert !base.modules.limine.enable;
assert base.modules.limine.splashImage == null;
assert !base.boot.plymouth.enable;
assert disabledWithImage.boot.plymouth.enable == base.boot.plymouth.enable;
assert disabledWithImage.boot.plymouth.theme == base.boot.plymouth.theme;
assert disabledWithImage.boot.plymouth.themePackages == base.boot.plymouth.themePackages;
assert !disabledWithImage.boot.loader.limine.enable;
assert !base.boot.loader.limine.enable;
assert !base.boot.loader.systemd-boot.enable;
assert lib.all (param: !(lib.elem param base.boot.kernelParams)) defaultParams;
assert enabled.modules.limine.enable;
assert enabled.boot.loader.limine.enable;
assert !enabled.boot.loader.systemd-boot.enable;
assert enabled.boot.loader.efi.canTouchEfiVariables;
assert enabled.boot.loader.limine.maxGenerations == 10;
assert enabled.boot.kernelPackages.kernel.version == pkgs.linuxPackages.kernel.version;
assert enabled.boot.plymouth.enable;
assert enabled.modules.limine.splashImage == null;
assert enabled.boot.plymouth.theme == base.boot.plymouth.theme;
assert enabled.boot.plymouth.themePackages == base.boot.plymouth.themePackages;
assert custom.boot.plymouth.enable;
assert toString custom.modules.limine.splashImage == toString image;
assert custom.boot.plymouth.theme == "centered-logo";
assert map (p: p.drvPath) custom.boot.plymouth.themePackages == [ themePackage.drvPath ];
assert lib.hasInfix (builtins.unsafeDiscardStringContext (
  lib.escapeShellArg image
)) themePackage.buildCommand;
assert lib.hasInfix "-resize '960x360>'" themePackage.buildCommand;
assert lib.hasInfix "$out/share/plymouth/themes/centered-logo" themePackage.buildCommand;
assert lib.hasInfix "$themeDir/logo.png" themePackage.buildCommand;
assert
  themePackage.drvPath != (t.attopkgs.centered-plymouth-theme {
    image = pkgs.writeText "other-splash.ppm" "P3\n1 1\n255\n0 0 0\n";
  }).drvPath;
assert lib.hasSuffix ".drv" custom.system.build.toplevel.drvPath;
assert customOverridden.boot.plymouth.theme == "native-theme";
assert
  map (p: p.drvPath) customOverridden.boot.plymouth.themePackages == [ nativeThemePackage.drvPath ];
assert lib.hasSuffix ".drv" customOverridden.system.build.toplevel.drvPath;
assert enabled.boot.consoleLogLevel == 3;
assert !enabled.boot.initrd.verbose;
assert lib.all (param: lib.elem param enabled.boot.kernelParams) defaultParams;
assert lib.all (param: !(lib.elem param enabled.boot.kernelParams)) unsafeParams;
assert overridden.boot.kernelPackages.kernel.version == pkgs.linuxPackages_latest.kernel.version;
assert lib.elem "debug" overridden.boot.kernelParams;
assert lib.elem "loglevel=7" overridden.boot.kernelParams;
assert lib.all (param: !(lib.elem param overridden.boot.kernelParams)) defaultParams;
assert overridden.boot.consoleLogLevel == 7;
assert overridden.boot.initrd.verbose;
assert !overridden.boot.plymouth.enable;
assert overridden.boot.loader.limine.maxGenerations == 3;
assert !overridden.boot.loader.efi.canTouchEfiVariables;
true
